### ISSUE TITLE
link for FlashPro files and Linux images corrupted

### ISSUE THREAD

**Issue by OrlyShdema** [polarfire-soc/polarfire-soc-documentation#3]
Hi ,

links for FlashPro files and Linux images  are corrupted and the files can not be downloaded..
Pls. advise.

Thanks,
Orly

**Comment by OrlyShdema** [comment]
for the icicle kit

**Comment by hughbreslin** [comment]
Hey Orly, 

thanks for letting us know, we'll try and get those links fixed asap 🙂 

Hugh

**Comment by hughbreslin** [comment]
Hi Orly, 

could you try using a different browser and let me know if the links work for you? I primarily use Chrome and that won't open the links but trying to download the files using Internet Explorer does.

**Comment by kevinscully100** [comment]
The files download and unzip ok for me using Firefox

**Comment by OrlyShdema** [comment]
with windows explorer it works
with chrome it doesn't work.

**Comment by hughbreslin** [comment]
Hey @OrlyShdema we're providing these files as assets with the [releases](https://github.com/polarfire-soc/icicle-kit-reference-design/releases) now, can you check this is working for you? 🙂

**Comment by Cyril-Jean** [comment]
Resolved by providing FPGA programming files and Linux images as GitHub assets.
