### ISSUE TITLE
Incorrect link in MPFS Discovery Kit User Guide

### ISSUE THREAD

**Issue by TM95134** [polarfire-soc/polarfire-soc-documentation#420]
The reference section in the MPFS Discovery Kit User Guide (https://github.com/polarfire-soc/polarfire-soc-documentation/blob/master/reference-designs-fpga-and-development-kits/mpfs-discovery-kit-user-guide.md) contains a link to the PolarFire SoC Icicle Kit Product page. Clicking this link goes to the PolarFire SoC Discovery Kit page (https://www.microchip.com/en-us/development-tool/mpfs-disco-kit). Should the name in the Reference section be PolarFire SoC Discovery Kit Product page?

**Comment by vfalanis** [comment]
Hi,
Thanks for reporting. The document is now referencing the Discovery Kit.
