### ISSUE TITLE
Text in MPFS Discovery Kit User Guide

### ISSUE THREAD

**Issue by TM95134** [polarfire-soc/polarfire-soc-documentation#421]
In the Updating section of the MPFS Discovery Kit User Guide (https://github.com/polarfire-soc/polarfire-soc-documentation/blob/master/reference-designs-fpga-and-development-kits/mpfs-discovery-kit-user-guide.md#updating) says "Linux images for the Icicle Kit are available from the releases section of the Meta PolarFire SoC Yocto BSP. The link for Meta PolarFire SoC Yocto BSP goes to a page titled Pre-built images for the Discovery Kit Reference Design. Should "Linux images for the Icicle Kit are available .." be "Linux images for the Discovery Kit are available ..."

**Comment by vfalanis** [comment]
Hi,
Thanks for reporting. The document is now referencing the Discovery Kit.
