### ISSUE TITLE
usbdmsc command stuck at "Waiting for USB Host to connect"

### ISSUE THREAD

**Issue by taovcu** [polarfire-soc/polarfire-soc-documentation#9]
[15.311310] HSS_TinyCLI_Parser(): >> usbdmsc
Waiting for USB Host to connect... (CTRL-C to quit)

Any idea? Thanks.

**Comment by kevinscully100** [comment]
Is this the same issue as [eMMC does not expose as a mass storage device](https://github.com/polarfire-soc/polarfire-soc-documentation/issues/9)? Can this be closed as a duplicate issue?

**Comment by taovcu** [comment]
Hi @kevinscully100 

Yes, the same issue and I close it here. Thanks.
